name = "python-sdk"
engineVersion = "v1.0.0-beta.14"
include = ["!.dagger", "!future", "!docs"]

[runtime]
source = "dang"

[[dependencies]]
name = "sdk-helpers"
source = "dagger.io/sdk/helpers@v1"

[[dependencies]]
name = "python-sdk-runtime"
source = "runtime"
