"""One package per client, plus one for core, in `dagger_clients`.

And, only when asked, the temporary global client, `dagger_global`.
"""

import json
import pathlib
import textwrap
from collections.abc import Iterator, Sequence
from itertools import groupby

from graphql import (
    GraphQLField,
    GraphQLInterfaceType,
    GraphQLObjectType,
    GraphQLSchema,
    GraphQLType,
    Node,
    get_named_type,
)
from graphql.type.schema import TypeMap

from codegen import partition
from codegen.generator import (
    Context,
    _ObjectField,
    expected_type_name,
    format_name,
    indent,
    is_builtin_scalar_type,
    is_input_object_type,
    is_interface_type,
    is_object_type,
    joiner,
    legacy_id_names,
    legacy_sdk_compat,
    new_context,
    quote,
    render_types,
)

NAMESPACE = "dagger_clients"
"""Namespace package that every generated package goes into."""

GLOBAL = "dagger_global"
"""Package of the temporary global client, next to the SDK files."""

Files = dict[str, str]
"""Content of a package, by file name."""

SESSION_NAMES = frozenset(
    {
        "_as_session",
        "_loads",
        "_ready",
        "aclose",
        "close",
        "connect",
        "connection",
        "execute",
        "forget",
        "load",
        "session",
    }
)
"""What a `dagger.Session` has, which a method of the global client would hide."""

_HEADER = """\
# Code generated by dagger. DO NOT EDIT.

# Every helper goes by a private alias, so that no generated type shadows it.
import warnings as _warnings  # noqa: F401
from collections.abc import Callable as _Callable
from dataclasses import dataclass as _dataclass
from typing import Protocol as _Protocol
from typing import overload as _overload
from typing import runtime_checkable as _runtime_checkable

from typing_extensions import Self as _Self

%s
from dagger.client._core import Arg as _Arg
from dagger.client._guards import type_error as _type_error
from dagger.client.base import Enum as _Enum
from dagger.client.base import Input as _Input
from dagger.client.base import Root as _Root
from dagger.client.base import Scalar as _Scalar
from dagger.client.base import Type as _Type
"""


def _aliased(*names: str) -> str:
    return "\n".join(f"from dagger.client import {name} as _{name}" for name in names)


class _EntryField(_ObjectField):
    """Field of `Query` that is the way into a client."""

    def __init__(
        self,
        ctx: Context,
        name: str,
        field: GraphQLField,
        parent: GraphQLObjectType | GraphQLInterfaceType,
    ) -> None:
        super().__init__(ctx, name, field, parent)
        for arg in self.args:
            if arg.name == "session":
                arg.name = "session_"

    @property
    def label(self) -> str:
        return self.name

    @property
    def return_type(self) -> str:
        return self.type

    def params(self) -> Iterator[str]:
        yield from (a.as_param() for a in self.required_args)
        yield "*"
        yield from (a.as_param() for a in self.default_args)
        yield "session: _Session | None = None"

    @joiner
    def func_body(self) -> Iterator[str]:
        yield from self.func_prelude()
        yield (
            f"return _client_root({self.type}, _TARGET, "
            f'"{self.graphql_name}", _args, session=session)'
        )

    def render(self) -> str:
        return _block(self.func_signature(), indent(self.func_body()))


class _ContributedField(_ObjectField):
    """Field that a client contributes to a core type, as a function."""

    def __init__(
        self,
        ctx: Context,
        name: str,
        field: GraphQLField,
        parent: GraphQLObjectType | GraphQLInterfaceType,
    ) -> None:
        super().__init__(ctx, name, field, parent)
        self.receiver = format_name(parent.name)
        self.receiver_is_interface = is_interface_type(parent)
        self.receiver_class = (
            f"_{parent.name}Client" if self.receiver_is_interface else parent.name
        )
        if self.receiver in {arg.name for arg in self.args}:
            self.receiver += "_"
        for arg in self.args:
            # A function has no `Self` to name the receiver's type with.
            arg.is_self = False

    @property
    def label(self) -> str:
        return self.name

    @property
    def return_type(self) -> str:
        return self.type

    @property
    def private_name(self) -> str:
        """Name of the function when the public one dispatches on the receiver."""
        # The GraphQL type name, not the snake-cased receiver: with its capital
        # letter, the name can't spell the alias of a helper, like _client_select.
        return f"_{self.parent_name}_{self.name}"

    def params(self) -> Iterator[str]:
        # Positional only, because the name changes with the receiver's type
        # when the function is overloaded.
        yield f"{self.receiver}: {self.parent_name}"
        yield "/"
        yield from list(super().params())[1:]

    def select_expr(self) -> str:
        return f'_client_select({self.receiver}, _TARGET, "{self.graphql_name}", _args)'

    @joiner
    def func_body(self) -> Iterator[str]:
        if not self.convert_id:
            yield super().func_body()
            return
        # Never straight through the receiver's context, which would run the
        # query before the module is loaded: the selection needs the target.
        yield from self.func_prelude()
        yield f"_ctx = {self.select_expr()}"
        yield "_id = await _ctx.execute(_Scalar)"
        yield f'return {self.receiver_class}(_ctx.select_id("{self.parent_name}", _id))'

    def render(self, name: str | None = None) -> str:
        return _block(self.func_signature(name), indent(self.func_body()))


def _block(*lines: str) -> str:
    """A top level statement, with the blank lines that set it apart."""
    return "\n".join(("", *lines, ""))


def _render_overloaded(name: str, fields: list[_ContributedField]) -> Iterator[str]:
    yield from (f.render(f.private_name) for f in fields)
    yield from (_block("@_overload", f"{f.func_signature()} ...") for f in fields)

    # By the exact GraphQL type first: an interface is a runtime-checkable
    # protocol, so an object that implements it would match structurally and
    # take the interface's hook, with the wrong arguments. The structural
    # match is only the fallback for an object that has no hook of its own.
    def _dispatch(f: _ContributedField, condition: str) -> str:
        return indent(
            f"if {condition}:\n    return {f.private_name}(receiver, *args, **kwargs)"
        )

    expected = " | ".join(f.parent_name for f in fields)
    yield _block(
        f"def {name}(receiver, /, *args, **kwargs):",
        indent(
            "_name = receiver._graphql_name() if isinstance(receiver, _Type) else None"
        ),
        *(_dispatch(f, f'_name == "{f.parent_name}"') for f in fields),
        *(
            _dispatch(f, f"isinstance(receiver, {f.parent_name})")
            for f in fields
            if f.receiver_is_interface
        ),
        indent(f'raise _type_error("{name}", "receiver", receiver, "{expected}")'),
    )


def _owned(schema: GraphQLSchema, module: str | None) -> TypeMap:
    return {
        name: t
        for name, t in schema.type_map.items()
        if partition.source_module(t.ast_node) == module
    }


def _all(names: list[str]) -> str:
    return _block(
        "__all__ = [",
        *(indent(f"{quote(name)},") for name in sorted(names)),
        "]",
    )


@joiner
def _core_init(schema: GraphQLSchema, schema_version: str) -> Iterator[str]:
    ctx = new_context(schema, schema_version, partitioned=True)
    digest = partition.core_digest(schema, legacy_sdk_compat=ctx.legacy_sdk_compat)

    yield _HEADER % _aliased("Session", "client_root")
    yield from render_types(ctx, _owned(schema, None))
    yield _block(
        "def core(*, session: _Session | None = None) -> Query:",
        indent('"""The way into the core API."""'),
        indent("return _client_root(Query, None, None, [], session=session)"),
    )
    yield _block(
        f"CORE_DIGEST = {quote(digest)}",
        '"""Digest of the core schema that this package was generated from."""',
    )
    yield _all([*ctx.defined, "CORE_DIGEST", "core"])


def _type_names(schema: GraphQLSchema, module: str | None, *, legacy: bool) -> set[str]:
    """Public names that the package of a module, or of core, defines."""
    owned = _owned(schema, module)
    names = set(legacy_id_names(owned)) if legacy else set()
    names |= {
        name
        for name, t in owned.items()
        if not name.startswith("_") and not is_builtin_scalar_type(t)
    }
    return names


def _core_names(ctx: Context) -> set[str]:
    """Every name that a client may import from the core package."""
    core = _owned(ctx.schema, None)
    return _type_names(ctx.schema, None, legacy=ctx.legacy_sdk_compat) | {
        f"_{name}Client" for name, t in core.items() if is_interface_type(t)
    }


def _find_module(schema: GraphQLSchema, name: str) -> tuple[str, str]:
    """The module of the schema that a client name stands for, and its package."""
    package = partition.package_name(name)
    packages = partition.package_names(partition.modules(schema))
    for module, module_package in packages.items():
        if module_package == package:
            return module, package
    msg = (
        f'the schema attributes nothing to the client "{name}"; '
        f"it has: {', '.join(packages) or 'no module'}"
    )
    raise partition.ClientError(msg)


def _references(schema: GraphQLSchema, module: str, owned: TypeMap) -> dict[str, str]:
    """Types that the code of a client names, and one place that names each."""
    places: list[tuple[str, GraphQLType, Node | None]] = []
    members = [
        (t, name, f)
        for t in owned.values()
        if is_object_type(t) or is_interface_type(t)
        for name, f in t.fields.items()
    ]
    for parent, name, f in [*partition.contributed_fields(schema, module), *members]:
        place = f"{parent.name}.{name}"
        places.append((place, f.type, f.ast_node))
        places += [(place, a.type, a.ast_node) for a in f.args.values()]
    for t in owned.values():
        if is_input_object_type(t):
            places += [
                (f"{t.name}.{name}", i.type, i.ast_node) for name, i in t.fields.items()
            ]

    names: dict[str, str] = {}
    for place, type_, node in places:
        names.setdefault(get_named_type(type_).name, place)
        if expected := expected_type_name(schema, node):
            names.setdefault(expected, place)
    return names


def _core_imports(ctx: Context, module: str, references: dict[str, str]) -> list[str]:
    """Names to import from core, refusing a name that another client owns."""
    available = _core_names(ctx)
    imports = set()
    for name, place in references.items():
        t = ctx.schema.get_type(name)
        owner = partition.source_module(t.ast_node) if t else None
        if owner not in (None, module):
            msg = (
                f'"{place}" of the client "{module}" names '
                f'"{name}" of the client "{owner}"'
            )
            raise partition.ClientError(msg)
        # The legacy ID and the concrete class of an interface go along with
        # the type, because the code that uses the type may use them too.
        imports |= {name, f"{name}ID", f"_{name}Client"} & available
    return sorted(imports)


@joiner
def _client_init(
    schema: GraphQLSchema, module: str, package: str, schema_version: str
) -> Iterator[str]:
    ctx = new_context(schema, schema_version, partitioned=True)
    owned = _owned(schema, module)

    entry: _EntryField | None = None
    contributed: list[_ContributedField] = []
    for parent, name, field in partition.contributed_fields(schema, module):
        # The entry is the `Query` field that the module contributes under its
        # own name, because that is the constructor the engine makes for it.
        # Any other `Query` field it contributes is a plain function.
        if parent.name == "Query" and name.lower() == package.replace("_", ""):
            entry = _EntryField(ctx, name, field, parent)
        else:
            contributed.append(_ContributedField(ctx, name, field, parent))

    if entry is None or not is_object_type(entry.named_type):
        msg = f'the schema has no constructor for the client "{module}"'
        raise partition.ClientError(msg)

    references = _references(schema, module, owned)
    references |= {f.parent_name: f.label for f in contributed}

    yield _HEADER.rstrip() % _aliased(
        "Session", "Target", "check_core", "client_root", "client_select"
    )
    yield f"from {NAMESPACE}.{partition.CORE} import CORE_DIGEST as _installed_core"
    yield ""
    yield "from ._target import CORE_DIGEST, NAME, PIN, REF"
    yield ""
    # Before any core symbol is imported: a stale core that dropped one would
    # otherwise raise a plain ImportError, and the message to regenerate would
    # never be seen.
    yield "_check_core(NAME, CORE_DIGEST, _installed_core)"
    # A client whose types name nothing of core has no block: an empty one
    # is a syntax error.
    if imports := _core_imports(ctx, module, references):
        yield ""
        yield f"from {NAMESPACE}.{partition.CORE} import (  # noqa: E402"
        yield from (indent(f"{name},") for name in imports)
        yield ")"
    # Private like the helpers: a client type named TARGET would otherwise
    # replace the descriptor, and the class itself would reach client_root.
    yield _block(
        "_TARGET = _Target(name=NAME, ref=REF, pin=PIN)",
        '"""The module that this client loads on first use."""',
    )
    yield from _client_body(ctx, owned, entry, contributed)


def _client_body(
    ctx: Context,
    owned: TypeMap,
    entry: _EntryField,
    contributed: list[_ContributedField],
) -> Iterator[str]:
    yield from render_types(ctx, owned)
    yield entry.render()

    functions = [entry.name]
    by_name = sorted(contributed, key=lambda f: (f.name, f.parent_name))
    for name, group in groupby(by_name, key=lambda f: f.name):
        fields = list(group)
        functions.append(name)
        if len(fields) == 1:
            yield fields[0].render()
        else:
            yield from _render_overloaded(name, fields)

    yield _all([*ctx.defined, *functions])


def _target(name: str, ref: str, pin: str | None, core_digest: str) -> str:
    # Plain data, so that reading the descriptor never needs the SDK.
    return textwrap.dedent(
        f"""\
        # Code generated by dagger. DO NOT EDIT.

        NAME = {json.dumps(name)}
        REF = {json.dumps(ref)}
        PIN = {json.dumps(pin) if pin else None}
        CORE_DIGEST = {json.dumps(core_digest)}
        """
    )


def core_package(schema: GraphQLSchema, schema_version: str = "") -> Files:
    """Files of `dagger_clients.core`, whatever clients the schema holds."""
    partition.check_attribution(schema)
    return {
        "__init__.py": _core_init(schema, schema_version),
        "py.typed": "",
    }


def client_package(  # noqa: PLR0913
    schema: GraphQLSchema,
    name: str,
    ref: str,
    pin: str | None = None,
    core_digest: str | None = None,
    schema_version: str = "",
) -> tuple[str, Files]:
    """Package name and files of one client, whatever the other clients are."""
    partition.check_attribution(schema)
    module, package = _find_module(schema, name)
    # The client's schema holds core, so the digest it must match is known.
    # A given one that differs would bless a client generated against other
    # core types, which is the skew that check_core is there to catch.
    expected = partition.core_digest(
        schema, legacy_sdk_compat=legacy_sdk_compat(schema_version)
    )
    if core_digest is None:
        core_digest = expected
    elif core_digest != expected:
        msg = (
            f'the core digest "{core_digest}" given for the client "{name}" '
            f"is not that of its schema's core, {expected}"
        )
        raise partition.ClientError(msg)
    return package, {
        "__init__.py": _client_init(schema, module, package, schema_version),
        "_target.py": _target(name, ref, pin, core_digest),
        "py.typed": "",
    }


_GLOBAL_HEADER = """\
# Code generated by dagger. DO NOT EDIT.
#
# Temporary. This global client keeps dag.container(), dag.linter() and
# dagger.Container working while a module moves to dagger_clients: one
# method per root field and per client, and every field a client
# contributes put back on its core class at import. It exists only with
# `global-client = true` under [tool.dagger], and the next `dagger generate`
# without the flag removes it.

from dagger.client import Session as _Session
"""


class _GlobalField(_ObjectField):
    """A method of the global client: the field, delegated to the new API."""

    def __init__(  # noqa: PLR0913
        self,
        ctx: Context,
        name: str,
        field: GraphQLField,
        parent: GraphQLObjectType | GraphQLInterfaceType,
        target: str,
        *,
        owner: str,
        receiver: str | None = None,
        entry: bool = False,
    ) -> None:
        super().__init__(ctx, name, field, parent)
        if self.name in SESSION_NAMES:
            # The method would replace what the session itself runs on, and
            # dag would then fail far from the field that caused it.
            msg = (
                f'the global client cannot have a method for "{parent.name}.{name}" '
                f"of {owner}: it would hide Session.{self.name}"
            )
            raise partition.ClientError(msg)
        self.target = target
        self.receiver_expr = receiver
        self.entry = entry
        for arg in self.args:
            # A method of the global client has no Self of the root type.
            arg.is_self = False

    @property
    def return_type(self) -> str:
        return self.type

    def params(self) -> Iterator[str]:
        yield "self"
        yield from (a.as_param() for a in self.required_args)
        if self.default_args:
            yield "*"
        yield from (a.as_param() for a in self.default_args)

    def _keyword(self, name: str) -> str:
        # The entry function renamed its `session` argument. The method keeps
        # the name the legacy client had, and passes it on under the new one.
        return "session_" if self.entry and name == "session" else name

    def render(self) -> str:
        args = [self.receiver_expr] if self.receiver_expr else []
        args += [a.name for a in self.required_args]
        args += [f"{self._keyword(a.name)}={a.name}" for a in self.default_args]
        if self.entry:
            args.append("session=self")
        call = f"{self.target}({', '.join(args)})"
        if self.is_void:
            body = f"await {call}"
        elif self.is_exec:
            body = f"return await {call}"
        else:
            body = f"return {call}"
        return "\n".join((self.func_signature(), indent(body)))


def _global_clients(
    schemas: Sequence[GraphQLSchema],
) -> dict[str, tuple[str, GraphQLSchema]]:
    """Module and schema of each client package, over every given schema."""
    clients: dict[str, tuple[str, GraphQLSchema]] = {}
    for schema in schemas:
        for module, package in partition.package_names(
            partition.modules(schema)
        ).items():
            known = clients.setdefault(package, (module, schema))
            if known[0] != module:
                msg = (
                    f'clients "{known[0]}" and "{module}" '
                    f'both become the package "{package}"'
                )
                raise partition.ClientNameError(msg)
    return clients


@joiner
def _global_init(
    schemas: Sequence[GraphQLSchema], schema_version: str
) -> Iterator[str]:
    core_schema = schemas[0]
    ctx = new_context(core_schema, schema_version, partitioned=True)
    legacy = ctx.legacy_sdk_compat
    clients = _global_clients(schemas)

    core_alias = f"_{partition.CORE}"
    core_root = f"{core_alias}.{partition.CORE}(session=self)"
    methods: list[_GlobalField] = []
    patches: list[tuple[str, str, str]] = []
    exported: set[str] = _type_names(core_schema, None, legacy=legacy)
    imports: list[str] = []

    query = core_schema.get_type("Query")
    if isinstance(query, GraphQLObjectType):
        methods += [
            _GlobalField(
                ctx,
                name,
                f,
                query,
                f"{core_root}.{format_name(name)}",
                owner=partition.CORE,
            )
            for name, f in partition.own_fields(query).items()
        ]

    for package, (module, schema) in sorted(clients.items()):
        alias = f"_{package}"
        names = sorted(_type_names(schema, module, legacy=legacy))
        exported |= set(names)
        if names:
            imports.append(f"from {NAMESPACE}.{package} import ({_lines(names)})")
        client_ctx = new_context(schema, schema_version, partitioned=True)
        owner = f'the client "{module}"'
        for parent, name, f in partition.contributed_fields(schema, module):
            function = format_name(name)
            if parent.name == "Query" and name.lower() == package.replace("_", ""):
                methods.append(
                    _GlobalField(
                        client_ctx,
                        name,
                        f,
                        parent,
                        f"{alias}.{function}",
                        owner=owner,
                        entry=True,
                    )
                )
            elif parent.name == "Query":
                methods.append(
                    _GlobalField(
                        client_ctx,
                        name,
                        f,
                        parent,
                        f"{alias}.{function}",
                        owner=owner,
                        receiver=core_root,
                    )
                )
            else:
                receiver = (
                    f"_{parent.name}Client"
                    if is_interface_type(parent)
                    else parent.name
                )
                patches.append((receiver, function, f"{alias}.{function}"))

    receivers = sorted({r for r, _, _ in patches if r.startswith("_")})
    yield _GLOBAL_HEADER
    yield f"import {NAMESPACE}.{partition.CORE} as {core_alias}"
    yield from (f"import {NAMESPACE}.{p} as _{p}" for p in sorted(clients))
    yield f"from {NAMESPACE}.{partition.CORE} import *  # noqa: F403"
    if receivers:
        yield f"from {NAMESPACE}.{partition.CORE} import ({_lines(receivers)})"
    yield from imports
    yield ""
    members = [
        '"""The API as methods on the default session, for code not migrated."""',
        *(m.render() for m in sorted(methods, key=lambda m: m.name)),
    ]
    yield _block("class Client(_Session):", indent("\n\n".join(members)))
    yield _block("dag = Client()", '"""The global client instance."""')
    if patches:
        yield ""
        yield "# On the core classes at run time only: type checkers do not see"
        yield "# these, which points to the migration."
        yield from (
            f"{receiver}.{name} = {function}  # type: ignore[attr-defined]"
            for receiver, name, function in sorted(set(patches))
        )
    yield _all([*exported, "Client", "dag"])


def _lines(names: Sequence[str]) -> str:
    return "\n" + "".join(indent(f"{name},") + "\n" for name in names)


def global_package(schemas: Sequence[GraphQLSchema], schema_version: str = "") -> Files:
    """Files of `dagger_global`, for core and every client the schemas hold.

    Each client is generated from a schema of core and that module, so the
    global client, which names them all, takes one schema per client.
    """
    if not schemas:
        msg = "the global client needs at least one schema"
        raise partition.ClientError(msg)
    legacy = legacy_sdk_compat(schema_version)
    digest = partition.core_digest(schemas[0], legacy_sdk_compat=legacy)
    for schema in schemas:
        partition.check_attribution(schema)
        other = partition.core_digest(schema, legacy_sdk_compat=legacy)
        if other != digest:
            msg = f"the schemas hold two cores, {digest} and {other}"
            raise partition.ClientError(msg)
    return {
        "__init__.py": _global_init(schemas, schema_version),
        "py.typed": "",
    }


def write_global(output: pathlib.Path, files: Files) -> pathlib.Path:
    """Write the global client package, which is no member of the namespace."""
    root = output / GLOBAL
    root.mkdir(parents=True, exist_ok=True)
    for name, content in files.items():
        (root / name).write_text(content)
    return root


def write_package(output: pathlib.Path, package: str, files: Files) -> pathlib.Path:
    """Write a package under the namespace, which itself gets no `__init__.py`."""
    root = output / NAMESPACE / package
    root.mkdir(parents=True, exist_ok=True)
    for name, content in files.items():
        (root / name).write_text(content)
    return root
