"""Render a module description as a static Dang entrypoint."""

from __future__ import annotations

import dataclasses
import hashlib
import json
import pathlib
from collections.abc import Iterator

from dagger.mod._describe import (
    ArgumentDescription,
    EnumDescription,
    FunctionDescription,
    ModuleDescription,
    ObjectDescription,
    TypeRef,
)
from dagger.mod._exceptions import BadUsageError

HEADER = "# Code generated by dagger. DO NOT EDIT.\n"

MANIFESTS = (".python-version", "pyproject.toml", "requirements.lock", "uv.lock")

SKIPPED_DIRS = frozenset({"sdk", ".venv", "__pycache__"})
"""Directory names that hold no module source, at any depth of the module.

Together with every dotted directory: the vendored library is generated, and a
virtual environment or a bytecode cache never reaches the module's container.
The rendered guard skips the same names, so both sides scan one set of files.
"""


@dataclasses.dataclass(frozen=True, slots=True)
class SourceFile:
    path: str
    digest: str


def write_entrypoint(
    desc: ModuleDescription,
    *,
    name: str,
    root: pathlib.Path,
    output: pathlib.Path,
) -> None:
    """Write types.dang and main.dang for the module at root."""
    output.mkdir(parents=True, exist_ok=True)
    (output / "types.dang").write_text(render_types(desc))
    (output / "main.dang").write_text(render_main(name, source_files(root)))


def source_files(root: pathlib.Path) -> list[SourceFile]:
    """The files that can change the description, with their engine digests.

    A manifest absent at generation gets an empty digest: the guard refuses the
    module when such a file appears later and changes what gets installed.
    """
    files = [root / name for name in MANIFESTS]
    files += sorted(f for f in root.rglob("*.py") if _is_source(f.relative_to(root)))
    return [
        SourceFile(
            f.relative_to(root).as_posix(),
            file_digest(f.read_bytes()) if f.is_file() else "",
        )
        for f in files
    ]


def _is_source(rel: pathlib.PurePath) -> bool:
    return not any(d in SKIPPED_DIRS or d.startswith(".") for d in rel.parts[:-1])


def file_digest(data: bytes) -> str:
    """What File.digest(excludeMetadata: true) returns for these bytes."""
    inner = hashlib.sha256(data).digest()
    return "sha256:" + hashlib.sha256(inner).hexdigest()


def render_types(desc: ModuleDescription) -> str:
    lines = [HEADER, "type ModuleTypes {", "  pub all: [TypeDef!]! {", "    ["]
    for obj in desc.objects:
        lines += _indent(_object(obj), 6)
        lines[-1] += ","
    for enum in desc.enums:
        lines += _indent(_enum(enum), 6)
        lines[-1] += ","
    lines += ["    ]", "  }", "}", ""]
    return "\n".join(lines)


def render_main(name: str, files: list[SourceFile]) -> str:
    file_lines = "".join(
        f"    SourceFile(path: {_quote(f.path)}, digest: {_quote(f.digest)}),\n"
        for f in files
    )
    return MAIN_TEMPLATE.format(
        header=HEADER,
        name=_quote(name),
        files=file_lines,
        skipped=", ".join(_quote(d) for d in sorted(SKIPPED_DIRS)),
    )


def _object(obj: ObjectDescription) -> list[str]:
    description = _opt("description", obj.description)
    if obj.interface:
        head = f"typeDef.withInterface({_quote(obj.name)}{description})"
    else:
        deprecated = _opt("deprecated", obj.deprecated)
        head = f"typeDef.withObject({_quote(obj.name)}{description}{deprecated})"
    lines = [head]
    lines.extend(
        f".withField({_quote(field.name)}, {_type(field.type)}"
        f"{_opt('description', field.description)}"
        f"{_opt('deprecated', field.deprecated)})"
        for field in obj.fields
    )
    for func in obj.functions:
        lines += _wrap("withFunction", _function(func))
    if obj.constructor is not None:
        lines += _wrap("withConstructor", _function(obj.constructor))
    return lines


def _function(func: FunctionDescription) -> list[str]:
    if func.cache is not None:
        msg = (
            f"function '{func.name}' sets cache={func.cache!r}: a static entrypoint "
            "cannot honour cache policies; set dangEntrypoint = false to keep "
            "discovering types at runtime"
        )
        raise BadUsageError(msg)
    lines = [f"function({_quote(func.name)}, {_type(func.returns)})"]
    if func.description:
        lines.append(f".withDescription({_quote(func.description)})")
    if func.deprecated:
        lines.append(f".withDeprecated(reason: {_quote(func.deprecated)})")
    for flag, call in (
        (func.check, "withCheck"),
        (func.generator, "withGenerator"),
        (func.service, "withUp"),
        (func.agent, "withAgent"),
    ):
        if flag:
            lines.append(f".{call}")
    lines += [_argument(arg) for arg in func.args]
    return lines


def _argument(arg: ArgumentDescription) -> str:
    type_expr = _type(arg.type)
    if arg.nullable:
        type_expr += ".withOptional(true)"
    default = ""
    if arg.default_value is not None:
        default = f", defaultValue: ({_quote(arg.default_value)} :: Dagger.JSON!)"
    ignore = ""
    if arg.ignore is not None:
        ignore = f", ignore: [{', '.join(_quote(p) for p in arg.ignore)}]"
    return (
        f".withArg({_quote(arg.name)}, {type_expr}"
        f"{_opt('description', arg.description)}{default}"
        f"{_opt('defaultPath', arg.default_path)}"
        f"{_opt('defaultAddress', arg.default_address)}{ignore}"
        f"{_opt('deprecated', arg.deprecated)})"
    )


def _enum(enum: EnumDescription) -> list[str]:
    lines = [
        f"typeDef.withEnum({_quote(enum.name)}{_opt('description', enum.description)})"
    ]
    lines += [
        f".withEnumMember({_quote(m.name)}, value: {_quote(m.value)}"
        f"{_opt('description', m.description)}{_opt('deprecated', m.deprecated)})"
        for m in enum.members
    ]
    return lines


def _type(ref: TypeRef) -> str:
    expr = "typeDef"
    if ref.optional:
        expr += ".withOptional(true)"
    match ref.kind:
        case "LIST_KIND":
            assert ref.elem is not None
            return f"{expr}.withListOf({_type(ref.elem)})"
        case "ENUM_KIND":
            described = f"{_quote(ref.name)}{_opt('description', ref.description)}"
            return f"{expr}.withEnum({described})"
        case "SCALAR_KIND":
            described = f"{_quote(ref.name)}{_opt('description', ref.description)}"
            return f"{expr}.withScalar({described})"
        case "INTERFACE_KIND":
            return f"{expr}.withInterface({_quote(ref.name)})"
        case "OBJECT_KIND":
            return f"{expr}.withObject({_quote(ref.name)})"
        case _:
            return f"{expr}.withKind(TypeDefKind.{ref.kind})"


def _opt(arg: str, value: str | None) -> str:
    """A named string argument, omitted when there is nothing to say."""
    return f", {arg}: {_quote(value)}" if value else ""


def _quote(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def _wrap(call: str, body: list[str]) -> Iterator[str]:
    yield f".{call}("
    yield from _indent(body, 2)
    yield ")"


def _indent(lines: list[str], width: int) -> list[str]:
    pad = " " * width
    return [pad + line if i == 0 else pad + "  " + line for i, line in enumerate(lines)]


MAIN_TEMPLATE = """{header}
type Entrypoint implements ModuleEntrypoint {{
  let moduleName: String! = {name}
  let skippedDirs: [String!]! = [{skipped}]
  let sourceFiles: [SourceFile!]! = [
{files}  ]

  pub types(workspace: Workspace!): [TypeDef!]! {{
    ModuleTypes().all
  }}

  pub call(
    workspace: Workspace!,
    receiverType: String!,
    receiverValue: JSON,
    fnName: String!,
    fnArgs: JSON!,
  ): JSON! {{
    let request = JSON.encode({{{{
      receiverType: receiverType,
      receiverValue: receiverValue,
      fnName: fnName,
      fnArgs: fnArgs,
    }}}})
    let result = runtime
      .withExec(["python", "-m", "dagger.mod", "call", "--output", "/dagger/result.json"], stdin: request, experimentalPrivilegedNesting: true)
      .file("/dagger/result.json")
      .contents
    (result :: JSON!)
  }}

  # The module's own source, not the workspace the engine hands over: that is
  # the caller's, which holds the module only when the module sits in it.
  let runtime: Container! {{
    let module = currentModule.source
    let changed = sourceFiles.filter {{ f =>
      if (f.digest == "") {{
        module.exists(f.path)
      }} else {{
        module.exists(f.path) == false or module.file(f.path).digest(excludeMetadata: true) != f.digest
      }}
    }}.map {{ f => f.path }}
    let added = module.glob("**/*.py").filter {{ p =>
      isSource(p) and sourceFiles.filter {{ f => f.path == p }}.length == 0
    }}
    if ((changed + added).length > 0) {{
      raise "module \\"" + moduleName + "\\" changed since its entrypoint was generated (" + (changed + added).join(", ") + "); run `dagger generate`"
    }} else {{
      PythonModuleBuild(
        contextDir: directory.withDirectory(".", module, exclude: ["**/.venv", "**/__pycache__"]),
        subPath: ".",
        moduleName: moduleName,
      ).installed
    }}
  }}

  let isSource(path: String!): Boolean! {{
    path.split("/").dropLast(1).filter {{ segment =>
      segment.hasPrefix(".") or skippedDirs.contains(segment)
    }}.length == 0
  }}
}}

type SourceFile {{
  pub path: String!
  pub digest: String!

  new(path: String!, digest: String!) {{
    self.path = path
    self.digest = digest
    self
  }}
}}
"""
